# Generated by Django 3.2.6 on 2021-08-31 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_discountcode_title'),
        ('books', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='max_cash_off',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_cash_books', to='orders.cashoff', verbose_name='تخفیف نقدی'),
        ),
        migrations.AlterField(
            model_name='book',
            name='percent_off',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_percent_books', to='orders.percentoff', verbose_name='درصد تخفیف'),
        ),
    ]
