# Generated by Django 3.2.6 on 2021-08-11 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('books', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='max_cash_off',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cash_disc', to='payments.cashoff', verbose_name='تخفیف نقدی'),
        ),
        migrations.AlterField(
            model_name='book',
            name='percent_off',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='percent_disc', to='payments.percentoff', verbose_name='درصد تخفیف'),
        ),
    ]
