# Generated by Django 3.2.6 on 2021-08-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_active',
            field=models.BigIntegerField(default=True, verbose_name='در دسترس'),
        ),
    ]
