# Generated by Django 3.2.6 on 2021-08-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='is_active',
            field=models.BigIntegerField(choices=[('A', 'فعال'), ('D', 'غیرفعال')], default='A', verbose_name='در دسترس'),
        ),
    ]
