# Generated by Django 3.2.6 on 2021-08-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='is_active',
            field=models.BigIntegerField(choices=[(True, 'فعال'), (False, 'غیرفعال')], default=True, verbose_name='در دسترس'),
        ),
    ]
