# Generated by Django 3.2.6 on 2021-08-11 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('discount_type', models.CharField(choices=[('C', 'نقدی'), ('P', 'درصدی')], max_length=2, verbose_name='نوع تخفیف')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_basket', to='accounts.customer', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'سبدخرید',
                'verbose_name_plural': 'سبدهای خرید مشتریان',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='تعداد')),
                ('status', models.CharField(choices=[('R', 'ثبت شده'), ('O', 'سفارش')], default='O', max_length=2, verbose_name='وضعیت سفارش')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_orders', to='payments.basket', verbose_name='سبد خرید سفارش')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='books.book', verbose_name='کتاب')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('type', models.CharField(choices=[('Ch', 'نقدی'), ('P', 'درصدی'), ('Co', 'کدی')], max_length=2, verbose_name='نوع')),
                ('percent_off', models.IntegerField(blank=True, null=True, verbose_name='مقدار درصدی')),
                ('cash_off', models.IntegerField(blank=True, null=True, verbose_name='مقدار نقدی')),
                ('code', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد تخفیف')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='اعتبار تا')),
                ('status', models.CharField(choices=[('E', 'منقضی شده'), ('V', 'معتبر')], default='', max_length=2, verbose_name='وضعیت')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='disObj_registrar', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('editors', models.ManyToManyField(related_name='disObj_editor', to=settings.AUTH_USER_MODEL, verbose_name='ویرایشگر')),
            ],
            options={
                'verbose_name': 'تخفیف',
                'verbose_name_plural': 'تخفیف ها',
                'ordering': ['deadline'],
            },
        ),
        migrations.AddField(
            model_name='basket',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='discount_baskets', to='payments.discount', verbose_name='تخفیف'),
        ),
        migrations.CreateModel(
            name='CashOff',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payments.discount',),
        ),
        migrations.CreateModel(
            name='PercentOff',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payments.discount',),
        ),
    ]
