# Generated by Django 3.2.6 on 2021-08-15 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_basket', to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('type', models.CharField(choices=[('Ch', 'نقدی'), ('P', 'درصدی')], max_length=2, verbose_name='نوع')),
                ('percent_off', models.IntegerField(blank=True, null=True, verbose_name='مقدار درصدی')),
                ('cash_off', models.IntegerField(blank=True, null=True, verbose_name='مقدار نقدی')),
                ('min_price_off', models.BigIntegerField(verbose_name='حداقل قیمت')),
                ('code', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد تخفیف')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان')),
                ('status', models.CharField(choices=[('E', 'منقضی شده'), ('V', 'معتبر')], default='', max_length=2, verbose_name='وضعیت')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='disObj_registrar', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('editors', models.ManyToManyField(related_name='disObj_editor', to=settings.AUTH_USER_MODEL, verbose_name='ویرایشگر')),
            ],
            options={
                'verbose_name': 'تخفیف کددار',
                'verbose_name_plural': 'تخفیف های کددار',
                'ordering': ['end'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('status', models.CharField(choices=[('R', 'ثبت شده'), ('O', 'سفارش'), ('D', 'تحویل')], default='O', max_length=2, verbose_name='وضعیت سفارش')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='basket_orders', to='payments.basket', verbose_name='سبد خرید')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_orders', to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
                ('delivery_address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_addresses', to='accounts.address', verbose_name='آدرس سفارش')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='discount_orders', to='payments.discountcode', verbose_name='تخفیف')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش های مشتریان',
            },
        ),
        migrations.CreateModel(
            name='PercentOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('percent_off', models.IntegerField(blank=True, null=True, verbose_name='مقدار درصدی')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان')),
                ('status', models.CharField(choices=[('E', 'منقضی شده'), ('V', 'معتبر')], default='', max_length=2, verbose_name='وضعیت')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='percent_registrar', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('editors', models.ManyToManyField(related_name='percent_editor', to=settings.AUTH_USER_MODEL, verbose_name='ویرایشگر')),
            ],
            options={
                'verbose_name': 'تخفیف درصدی',
                'verbose_name_plural': 'تخفیف های درصدی',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='تعداد')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='books.book', verbose_name='کتاب')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='payments.order', verbose_name='سفارش مربوطه')),
            ],
            options={
                'verbose_name': 'مورد سفارش',
                'verbose_name_plural': 'موارد سفارش',
            },
        ),
        migrations.CreateModel(
            name='CashOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('cash_off', models.IntegerField(blank=True, null=True, verbose_name='مقدار نقدی')),
                ('min_price_off', models.BigIntegerField(verbose_name='حداقل قیمت')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان')),
                ('status', models.CharField(choices=[('E', 'منقضی شده'), ('V', 'معتبر')], default='', max_length=2, verbose_name='وضعیت')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cash_registrar', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('editors', models.ManyToManyField(related_name='cash_editor', to=settings.AUTH_USER_MODEL, verbose_name='ویرایشگر')),
            ],
            options={
                'verbose_name': 'تخفیف نقدی',
                'verbose_name_plural': 'تخفیف های نقدی',
            },
        ),
    ]
