# Generated by Django 3.2.6 on 2021-08-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'مدیر'), (2, 'کارمند'), (3, 'مشتری')], null=True, verbose_name='سمت کاربر'),
        ),
    ]
