# Generated by Django 3.2.6 on 2021-08-15 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name': 'سبد خرید مشتری', 'verbose_name_plural': 'سبدهای خرید مشتریان'},
        ),
    ]
