# Generated by Django 3.2.6 on 2021-08-31 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashoff',
            name='editors',
        ),
        migrations.RemoveField(
            model_name='discountcode',
            name='editors',
        ),
        migrations.RemoveField(
            model_name='percentoff',
            name='editors',
        ),
        migrations.AddField(
            model_name='cashoff',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cash_editor', to=settings.AUTH_USER_MODEL, verbose_name='آخرین ویرایش توسط'),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='disObj_editor', to=settings.AUTH_USER_MODEL, verbose_name='آخرین ویرایش توسط'),
        ),
        migrations.AddField(
            model_name='percentoff',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='percent_editor', to=settings.AUTH_USER_MODEL, verbose_name='آخرین ویرایش توسط'),
        ),
    ]
