# Generated by Django 3.2.6 on 2021-08-31 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210831_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='عنوان'),
        ),
    ]
