# Generated by Django 3.2.6 on 2021-09-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210903_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='percent_off',
            field=models.IntegerField(blank=True, null=True, verbose_name='مقدار درصدی'),
        ),
        migrations.AlterField(
            model_name='percentoff',
            name='percent_off',
            field=models.IntegerField(blank=True, null=True, verbose_name='مقدار درصدی'),
        ),
    ]
