# Generated by Django 3.2.6 on 2021-09-03 05:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210903_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='percent_off',
            field=models.IntegerField(blank=True, null=True, verbose_name=django.core.validators.MaxValueValidator(100)),
        ),
        migrations.AlterField(
            model_name='percentoff',
            name='percent_off',
            field=models.IntegerField(blank=True, null=True, verbose_name=django.core.validators.MaxValueValidator(100)),
        ),
    ]
